# Generated by Django 5.1.5 on 2025-01-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0005_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
    ]
