# Generated by Django 5.1.5 on 2025-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0011_alter_ticket_creation_time_alter_ticket_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='display_color',
            field=models.CharField(default='#000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_logged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='time_logged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='time_logged',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
