# Generated by Django 5.1.5 on 2025-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0012_alter_priority_display_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time_logged',
        ),
        migrations.AlterField(
            model_name='priority',
            name='display_color',
            field=models.TextField(default='#000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='time_logged',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='time_logged',
            field=models.FloatField(),
        ),
    ]
