# Generated by Django 5.1.6 on 2025-03-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0014_ticket_time_logged_alter_ticket_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_view_status', 'Can view ticket status'), ('can_change_status', 'Can change ticket status'), ('can_assign_ticket', 'Can assign tickets')]},
        ),
    ]
