# Generated by Django 5.1.6 on 2025-04-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0019_profile_account_status_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
