# Generated by Django 5.1.6 on 2025-04-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0021_alter_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_status',
        ),
    ]
