# Generated by Django 5.1.5 on 2025-01-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
