# Generated by Django 5.1.5 on 2025-01-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('assign_ticket', 'Can assign tickets')]},
        ),
    ]
