# Generated by Django 5.1.5 on 2025-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0008_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
