# Generated by Django 5.1.5 on 2025-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0010_alter_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
