# Generated by Django 5.1.5 on 2025-01-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleticket', '0013_remove_ticket_time_logged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_logged',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
